from selenium import webdriver
import pageObjects
odpo = pageObjects.oVirtDashboardPageObjects()

def test_gluster_deployment_fail_check():
    odpo.setupLogFile('test_gluster_deployment_fail_check')
    driver = odpo.setup()
    odpo.open_page(driver)
    odpo.login(driver)
    odpo.time_sleep(15)
    odpo.switchFrame(driver, odpo.heFrame)
    odpo.assertHostedEngine(driver)
    odpo.time_sleep(5)
    odpo.startGlusterDeployment(driver)
    odpo.startThreeNodeWizard(driver)
    odpo.sendHostValuesForThreeNodeDep(driver, odpo.host1InputValue, odpo.host2InputValue, odpo.host3InputValue)
    odpo.wizardNextClick(driver)
    odpo.fqdnAssertCheck(driver)
    odpo.wizardNextClick(driver)
    odpo.packageAssertCheck(driver)
    odpo.wizardNextClick(driver)
    odpo.volumeAssertCheck(driver, True)
    odpo.volumeAddCheck(driver, odpo.EmptyVolumeNameValue)
    odpo.wizardNextClick(driver)
    odpo.raidAssertCheck(driver)
    odpo.raidTypeChange(driver, odpo.RaidTypeDropDownTextAlter)
    odpo.wizardNextClick(driver)
    odpo.assertPreview(driver)
    odpo.deployGluster(driver)
    odpo.spinnerCheck(driver)
    odpo.deploymentFailCheck(driver)
    odpo.driver_close(driver)

def test_gluster_empty_host_validation_check():
    odpo.setupLogFile('test_gluster_empty_host_validation_check')
    driver = odpo.setup()
    odpo.open_page(driver)
    odpo.login(driver)
    odpo.time_sleep(15)
    odpo.switchFrame(driver, odpo.heFrame)
    odpo.assertHostedEngine(driver)
    odpo.time_sleep(5)
    odpo.startGlusterDeployment(driver)
    odpo.startThreeNodeWizard(driver)
    odpo.wizardNextClick(driver)
    odpo.emptyHostAssertCheck(driver)
    odpo.driver_close(driver)

def test_gluster_fqdn_validation_check():
    odpo.setupLogFile('test_gluster_fqdn_validation_check')
    driver = odpo.setup()
    odpo.open_page(driver)
    odpo.login(driver)
    odpo.time_sleep(15)
    odpo.switchFrame(driver, odpo.heFrame)
    odpo.assertHostedEngine(driver)
    odpo.time_sleep(5)
    odpo.startGlusterDeployment(driver)
    odpo.startThreeNodeWizard(driver)
    odpo.sendHostValuesForThreeNodeDep(driver, odpo.host1InputValue, odpo.host2InputValue, odpo.host3InputValue)
    odpo.wizardNextClick(driver)
    odpo.fqdnAssertCheck(driver)
    odpo.handleSameFqdnAsHostCheck(driver)
    odpo.time_sleep(1)
    odpo.fqdnUnreachableErrorCheck(driver)
    odpo.handleSameFqdnAsHostCheck(driver)
    odpo.time_sleep(1)
    odpo.fqdnInput(driver, odpo.validFqdn, odpo.validFqdn)
    odpo.wizardNextClick(driver)
    odpo.fqdnSameError(driver)
    odpo.fqdn2Clear(driver)
    odpo.wizardNextClick(driver)
    odpo.driver_close(driver)

def test_gluster_volume_validation_check():
    odpo.setupLogFile('test_gluster_volume_validation_check')
    driver = odpo.setup()
    odpo.open_page(driver)
    odpo.login(driver)
    odpo.time_sleep(15)
    odpo.switchFrame(driver, odpo.heFrame)
    odpo.assertHostedEngine(driver)
    odpo.time_sleep(5)
    odpo.startGlusterDeployment(driver)
    odpo.startThreeNodeWizard(driver)
    odpo.sendHostValuesForThreeNodeDep(driver, odpo.host1InputValue, odpo.host2InputValue, odpo.host3InputValue)
    odpo.wizardNextClick(driver)
    odpo.fqdnAssertCheck(driver)
    odpo.wizardNextClick(driver)
    odpo.packageAssertCheck(driver)
    odpo.wizardNextClick(driver)
    odpo.volumeAssertCheck(driver, True)
    odpo.wizardNextClick(driver)
    odpo.deleteVolumeRow(driver, odpo.deleteVolumeIcon)
    odpo.wizardNextClick(driver)
    odpo.raidAssertCheck(driver)
    odpo.driver_close(driver)

def test_gluster_vdo_present():
    odpo.setupLogFile('test_gluster_vdo_present')
    driver = odpo.setup()
    odpo.open_page(driver)
    odpo.login(driver)
    odpo.time_sleep(15)
    odpo.switchFrame(driver, odpo.heFrame)
    odpo.assertHostedEngine(driver)
    odpo.time_sleep(5)
    odpo.startGlusterDeployment(driver)
    odpo.startThreeNodeWizard(driver)
    odpo.sendHostValuesForThreeNodeDep(driver, odpo.host1InputValue, odpo.host2InputValue, odpo.host3InputValue)
    odpo.wizardNextClick(driver)
    odpo.fqdnAssertCheck(driver)
    odpo.wizardNextClick(driver)
    odpo.packageAssertCheck(driver)
    odpo.wizardNextClick(driver)
    odpo.volumeAssertCheck(driver, False)
    odpo.wizardNextClick(driver)
    odpo.raidAssertCheck(driver)
    odpo.vdoCheck(driver)
    odpo.driver_close(driver)

def test_gluster_single_node_deployment_fail_check():
    odpo.setupLogFile('test_gluster_single_node_deployment_fail_check')
    driver = odpo.setup()
    odpo.open_page(driver)
    odpo.login(driver)
    odpo.time_sleep(15)
    odpo.switchFrame(driver, odpo.heFrame)
    odpo.assertHostedEngine(driver)
    odpo.time_sleep(5)
    odpo.startGlusterDeployment(driver)
    odpo.startSingleNodeWizard(driver)
    odpo.sendHostValuesForSingleNodeDep(driver, odpo.host1InputValue)
    odpo.wizardNextClick(driver)
    odpo.packageAssertCheck(driver)
    odpo.wizardNextClick(driver)
    odpo.volumeAssertCheck(driver, True)
    odpo.volumeAddCheck(driver, odpo.EmptyVolumeNameValue)
    odpo.wizardNextClick(driver)
    odpo.raidAssertCheck(driver)
    odpo.wizardNextClick(driver)
    odpo.assertPreview(driver)
    odpo.deployGluster(driver)
    odpo.spinnerCheck(driver)
    odpo.deploymentFailCheck(driver)
    odpo.driver_close(driver)

def test_gluster_three_node_deployment_check():
    odpo.setupLogFile('test_gluster_three_node_deployment_check')
    driver = odpo.setup()
    odpo.open_page(driver)
    odpo.login(driver)
    odpo.time_sleep(30)
    odpo.switchFrame(driver, odpo.heFrame)
    odpo.assertHostedEngine(driver)
    odpo.time_sleep(10)
    odpo.startGlusterDeployment(driver)
    odpo.startThreeNodeWizard(driver)
    odpo.sendHostValuesForThreeNodeDep(driver, h1, h2, h3)
    odpo.wizardNextClick(driver)
    odpo.fqdnAssertCheck(driver)
    odpo.handleSameFqdnAsHostCheck(driver)
    odpo.wizardNextClick(driver)
    odpo.packageAssertCheck(driver)
    odpo.wizardNextClick(driver)
    odpo.volumeAssertCheck(driver, False)
    odpo.wizardNextClick(driver)
    odpo.raidAssertCheck(driver)
    odpo.changeBrickDetails(driver)
    odpo.wizardNextClick(driver)
    odpo.assertPreview(driver)
    odpo.time_sleep(30)
    odpo.deployGluster(driver)
    odpo.spinnerCheck(driver)
    odpo.deploymentSuccessCheck(driver)
    odpo.continueToHostedEngineButtonClick(driver)
    odpo.spinnerCheck(driver)
    odpo.addVmFqdn(driver)
    odpo.addVmFqdnMacAdd(driver)
    odpo.validateVmFqdn(driver)
    odpo.addVmPassword(driver)
    odpo.time_sleep(60)
    odpo.heWizardNextClick(driver)
    odpo.addHePassword(driver)
    odpo.heWizardNextClick(driver)
    odpo.time_sleep(30)
    odpo.prepareVmDeployment(driver)
    odpo.prepareVmSpinnerCheck(driver)
    odpo.heWizardNextClick(driver)
    odpo.changeHeDiskSize(driver)
    odpo.heWizardNextClick(driver)
    odpo.time_sleep(30)
    odpo.heDeployment(driver)
